### ISSUE TITLE
Month Label Positioning

### ISSUE THREAD

**Issue by onmondo** [nizarmah/calendar-javascript-lib#1]
Hi @nizarmah 

The positioning of month labels always start on first day of the month.
Please see screenshot below:
![image](https://cloud.githubusercontent.com/assets/6768671/22584468/7ac64fc4-ea2d-11e6-9e65-fc5c7bb0ff33.png)

Notice that the calendar dates starts with the label "Wednesday".

Can we make the labels starts with "Sunday"?

Thanks in advance.

**Comment by onmondo** [comment]
Hi @nizarmah , please ignore this issue. Had already figured out how to configure the calendar month label.

**Comment by nizarmah** [comment]
Haha, no worries! Sorry my response wasn't quick; I was at school. Glad to see you figured it out, and if there are any bugs you face, please let me know.

Have a great day!

**Comment by onmondo** [comment]
Hi @nizarmah , I have a question, how do you list all the events per month on the list (right side of the screen)?

Thanks in advance.

**Comment by nizarmah** [comment]
Yes, that is available in the `example.html`
The `var data` contains the events, its organized through some code and then `organizer.listEvents(Events)`
Where `var organizer` is the Organizer Object. And the `var Events` is the data cleaned.
