### ISSUE TITLE
I want to disable previous dates

### ISSUE THREAD

**Issue by manojrhr** [nizarmah/calendar-javascript-lib#10]
I am using this library in a project and need to disable the previous dates than today. Is this feature available in this library. Also want to show dates selected for which appointments are available.

**Comment by nizarmah** [comment]
Hello, can you explain more what do you mean by disabling previous dates? 
And maybe provide a small example about the dates selected for the appointments?

**Comment by manojrhr** [comment]
I don't want to allow user to select previous dates than today and want to show those dates diable or not clickable by user.

**Comment by nizarmah** [comment]
Then buddy, it is better if you use JQuery UI Date Picker, because my calendar does not support it, and the JQuery UI date picker would be more beneficial in your case.

**Comment by manojrhr** [comment]
Thanks @nizarmah. Is it possible to highlight those dates on which I have appointments.

**Comment by nizarmah** [comment]
Sadly, you cannot highlight the days which you have appointments. But you can disable those days if you have appointments.

To do that, I found you a StackOverflow thread that succeeds in doing that. Basically, before you show the date, you can check if this day is occupied or not; consequently, you disable it if it is.

https://stackoverflow.com/questions/2968414/disable-specific-days-of-the-week-on-jquery-ui-datepicker#2973696
