### ISSUE TITLE
How can I put the calendar in the center of my webpage, sorry I am new to webpage

### ISSUE THREAD

**Issue by CAROLZXYZXY** [nizarmah/calendar-javascript-lib#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nizarmah** [comment]
Helloo, everything is simpler with FlexBox, so I am gonna propose a FlexBox solution.

If you want an example for FlexBox centering, I have one here, in the body's CSS.
https://codepen.io/nizarmah/pen/LkjjWV

Here's a cool guide for FlexBox.
https://css-tricks.com/snippets/css/a-guide-to-flexbox/
