### ISSUE TITLE
Calendar is not defined

### ISSUE THREAD

**Issue by elpipita20** [nizarmah/calendar-javascript-lib#12]
Hello I import CDN links and I watch your base config for the calendar. After inputing javascript in the <script> tag I got this error. **Calendar is not defined** If I type calendar with small c it says **calendar is not a constructor**

![image](https://user-images.githubusercontent.com/24462215/46346174-77d18e80-c647-11e8-8729-7656b449c6c7.png)
![image](https://user-images.githubusercontent.com/24462215/46346231-a18ab580-c647-11e8-8197-d1c868325cae.png)
![image](https://user-images.githubusercontent.com/24462215/46346235-a8b1c380-c647-11e8-82e8-82b13afa85d1.png)

**Comment by nizarmah** [comment]
Hello, used the updated links please.

```
https://cdn.rawgit.com/nizarmah/calendar-javascript-lib/master/calendarorganizer.min.js
https://cdn.rawgit.com/nizarmah/calendar-javascript-lib/master/calendarorganizer.min.css
```
