### ISSUE TITLE
how to customise the calendar to highlight current date and is it possible to disable previous dates

### ISSUE THREAD

**Issue by hashmat0811** [nizarmah/calendar-javascript-lib#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nizarmah** [comment]
Hello, sorry for the really really late reply. I had finals and I couldn't answer earlier.

Alright, so the highlight current date is a CSS class, you can override that. 
The CSS class is `cjslib-day-today`.

To prevent from going back to old dates, just do this...
```
#calendarContainer-month-back,
#calendarContainer-month-next,
#calendarContainer-year-next,
#calendarContainer-year-back {
  display: none !important;
}
```

But people will still be able to click on the days of the next and previous month and switch accordingly.
