### ISSUE TITLE
how to Multiple select dates

### ISSUE THREAD

**Issue by xnodcorp** [nizarmah/calendar-javascript-lib#15]
multiple select dates in calendar

**Comment by nizarmah** [comment]
With the multiple date selection, you wish to preview all the events of those dates selected in the organizer's list, is that correct ? If so I can work on it starting tomorrow. But please confirm :)

**Comment by xnodcorp** [comment]
yeah correct. thanks my friend

**Comment by nizarmah** [comment]
alright, i'll let you know when it is done (: hopefully tomorrow, should be easy to do. 
and thank you for helping contribute ideas to this library!

**Comment by nizarmah** [comment]
Hey, sorry about that, a bit jammed on work related stuff. Can you give me till Monday and I'll have it done ?

**Comment by nizarmah** [comment]
![image](https://user-images.githubusercontent.com/5631091/58953394-ff573a80-879e-11e9-96e7-7c386627a55e.png)

Done dude! Instead of showing the multi-selected dates, I showed their events in a way as history. Let me know if you need anything else. Thanks again for the great suggestion!

**Comment by xnodcorp** [comment]
nice.... thanks dude

**Comment by nizarmah** [comment]
you are most welcome :D have a great day!
