### ISSUE TITLE
Add URL for events?

### ISSUE THREAD

**Issue by mariekythe2** [nizarmah/calendar-javascript-lib#19]
Hi, I think it would be a good option to be able to click on the event and it will go to a certain link etc. In my case I'm using your calendar for files which could be downloaded.  Thank you so much :)

**Comment by nizarmah** [comment]
Definitely, I think that is a great idea. I'll start working on it :D

**Comment by nizarmah** [comment]
Alright, so using it is gonna be quite simple. The new event format is as follows...

```
{
    startTime: "00:00",
    endTime: "24:00",
    text: "Christmas Day",
    link: "https://github.com/nizarmah" // this is optional :)
}
```

> As mentioned, the link is optional. You can include it if you want (fill it or leave it empty), and you can not include it if you want. :D 

Thanks a lot for your suggestion @mariekythe2 :heart: 
I'm so glad people still use my library, and I am always happy to add more stuff to it. So if you have more suggestions, feel free to mention them :+1:

**Comment by mariekythe2** [comment]
Wow that was fast! :) Thank you so much You are awesome!
