### ISSUE TITLE
Diffused days counted reverse

### ISSUE THREAD

**Issue by onmondo** [nizarmah/calendar-javascript-lib#2]
Hi,

Those diffused days are shown in reverse order.

**Comment by nizarmah** [comment]
Hey! 

Umm, I'm so sorry, I don't understand what you mean.
Is it possible if you can show me an image ? 
Like put it on CodePen, or like upload an image onto Imgur ? Thanks...

**Comment by onmondo** [comment]
I'm pointing at the diluted days on the calendar (as highlighted below). The first occurrence did not render correctly the diluted days. The latter part is correct.

![capture](https://user-images.githubusercontent.com/6768671/27424217-e2d28bf4-5766-11e7-8fff-02408310171d.PNG)

**Comment by nizarmah** [comment]
Hello again!

Sorry it took me so long to reply back, I just fixed it. It wasn't hard fixing it, I just was too busy those couple days... I'm sorry for the late reply again, and the bug should be fixed for you. Just update `library.js` and voila.

Thanks for reporting it.
