### ISSUE TITLE
Doesn't work on Samsung Browser

### ISSUE THREAD

**Issue by iipajcii** [nizarmah/calendar-javascript-lib#20]
I'm not sure why but, this calendar isn't generated when using Samsung browser. Not sure what the problem is, the area is just blank and no space is taken up

**Comment by nizarmah** [comment]
Oh! I'm sorry to hear that. I'll make sure to debug it and let you know ( : If you can send me details about your Android version and the Browser version too, it would be really helpful :slightly_smiling_face: 

I'll keep you updated on the progress I make on it

**Comment by nizarmah** [comment]
I'm sorry @iipajcii I haven't had time to look at it lately. I'll do so during this weekend. Sorry again :frowning_face:

**Comment by iipajcii** [comment]
When I tested it again about 2 months ago, it only happened when I loaded it from my localhost server. If the file was on my phone or on my production server it worked fine. I have no idea why. I'm not getting errors otherwise. I wouldn't stress about this

**Comment by nizarmah** [comment]
Thanks @iipajcii! I had trouble recreating the issue, so I slept on it for a while because I didn't have much time to spend on it properly.

Sorry about that!
