### ISSUE TITLE
25% of Events are Not Printing on the Organizer

### ISSUE THREAD

**Issue by sbennett08** [nizarmah/calendar-javascript-lib#21]
I am following the "Basic Usage" guide on your main GitHub page.

My goal is to pull a list of events from a MYSQL database, organizing those dates into JSON via PHP, and print the list into the "data" variable of the Javascript code.

These are examples of the records, for a single day, which aren't printing. The "4" icon shows up on that day's calendar view, but when I click on that day, the organizer displays it's placeholder text, instead of the event information.

Array ( [startTime] => 20:11:00 [endTime] => 16:11:00 [text] => 123 )
Array ( [startTime] => 20:05:00 [endTime] => 20:05:00 [text] => Event for DEV TEST )
Array ( [startTime] => 11:36:00 [endTime] => 12:36:00 [text] => TEST PRIVATE TICKET )
Array ( [startTime] => 11:32:00 [endTime] => 11:32:00 [text] => TEST EVENT )

To be clear, most of the events are printing. So, I know the data array itself is formatted correctly. Here's an example of events, for a single day, which are printing.

Array ( [startTime] => 07:00:00 [endTime] => 07:00:00 [text] => Project Due: Allenwalk Product Upload )
Array ( [startTime] => 00:00:00 [endTime] => 00:00:00 [text] => Fired Station 69 )

I've compared the format of the times and text between printing records, and non-printing records, and I can't see any pattern suggesting a specific kind of record (such as uppercase events) isn't being printed. 

I'm stumped. Any thoughts?

**To Reproduce**
No idea.

Here's clearer idea of the format of the "data" variable for the calendar.

2020:
        7:
           02: [{…}]
           07: Array(4)
               0: {startTime: " 20:11:00", endTime: " 16:11:00", text: "123"}
               1: {startTime: " 20:05:00", endTime: " 20:05:00", text: "Event for  DEV TEST"}
               2: {startTime: " 11:36:00", endTime: " 12:36:00", text: "TEST PRIVATE TICKET"}
               3: {startTime: " 11:32:00", endTime: " 11:32:00", text: "TEST EVENT"}

**Expected behavior**
I expected the organizer to post all the events for that given day. The calendar itself is displaying the correct number of events for that day, but the organizer just posts the placeholder text when you click on that day. The events for that day are not being printed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85.0.4183.102

**Comment by sbennett08** [comment]
![working_event](https://user-images.githubusercontent.com/55404397/94052351-aba2a300-fd8d-11ea-80df-a52997d968f0.PNG)
![not_working_event](https://user-images.githubusercontent.com/55404397/94052359-af362a00-fd8d-11ea-92ba-bef3ab17aa9e.PNG)

Here's a image of the working events, as well as the ones that aren't printing.

**Comment by nizarmah** [comment]
Oh my! I will look into this during the weekend @sbennett08 :slightly_frowning_face: I'm really sorry about that, but I have some work to do during the week. 

The issue is probably the format of the JSON, 
So here's the format that you should use

```js
var data = {                                  // dictionary
    year: {                                      // dictionary
        month: {                               // dictionary
            day: [                               // array
                // add here as many Event objects as you like
            ]
        }
    }
}
```

And the event object is:

```js
{
    startTime: "00:00",
    endTime: "24:00",
    text: "Christmas Day"
}
```

Send me your JSON output, if you can and I'll point out what's wrong exactly with it :+1: Again sorry for the quick response, I'll give a more detailed one in the weekend.

**Comment by sbennett08** [comment]
I printed the JS data object to the console. It's a long record (over 70
events), so I thought I'd send a few screenshots instead.

The "overview_record" will give you a large scale view of the object.

The "working_record" contains the format and data for two events which *are
*working.

The "failing_record" contains the format and data for four events which *are
not* working.

The raw record is big, as you can see. I can send you more, but it will be
a large email. lol.

The tricky part is I have to format the array in PHP and then print it in
JS as a JSON object. I might be able to modify the array a bit in JS,
before printing it, if that is an easier solution.

To clarify, these screenshots are the "Data" object being printed to the
console, so this is a screenshot of the data right before it's printed to
the calendar.

I look forward to working through this issue with you. Let me know if there
is anything else I can do on my end to work toward a solution.

Thanks!

Sincerely,

Seth Bennett

>

**Comment by sbennett08** [comment]
Here's another view which contains every level within the array. Hope it
helps.

**Comment by nizarmah** [comment]
Hey @sbennett08 :smile: Were you referring to any screenshots, because they aren't visible on my end :slightly_frowning_face:

By the way, I should be able to help with this issue during the week this time :slightly_smiling_face: I'm pretty sure it is a JSON issue, though. Here's why

> Here's clearer idea of the format of the "data" variable for the calendar.
> 
> 2020:
> 7:
> 02: [{…}]
> 07: Array(4)
> 0: {startTime: " 20:11:00", endTime: " 16:11:00", text: "123"}
> 1: {startTime: " 20:05:00", endTime: " 20:05:00", text: "Event for DEV TEST"}
> 2: {startTime: " 11:36:00", endTime: " 12:36:00", text: "TEST PRIVATE TICKET"}
> 3: {startTime: " 11:32:00", endTime: " 11:32:00", text: "TEST EVENT"}

Alright, so regarding `0`, `1`, `2`, and `3`, those need to be an array of objects too, even if there's a single object in the array. 

If you have any screenshots of the actual dictionary, it might be more helpful :slightly_smiling_face:

**Comment by sbennett08** [comment]
I see. I attached 4 images over the last two emails. I will attach  them
again to this email as well.

Can you see them?

If not, I can make an unlisted youtube video reviewing the issue, and send
you the link.

Just say the word :)

**Comment by nizarmah** [comment]
@sbennett08 I don't see them :( No need for a youtube video, can you send them through the GitHub UI instead of through email replies? Maybe that's the reason they aren't showing up on the ticket :thinking:

**Comment by sbennett08** [comment]
![overview_record](https://user-images.githubusercontent.com/55404397/94580177-746d3f80-022e-11eb-9a3c-f626998ee156.PNG)
![second_overview_record](https://user-images.githubusercontent.com/55404397/94580179-7505d600-022e-11eb-8482-567c0955f843.PNG)
![working_record](https://user-images.githubusercontent.com/55404397/94580180-759e6c80-022e-11eb-8041-25b1e672d71e.PNG)
![failing_record](https://user-images.githubusercontent.com/55404397/94580181-759e6c80-022e-11eb-8365-c524bcca22f7.PNG)

Can you see these?

**Comment by sbennett08** [comment]
From these examples, the date: 7/07 is the one that's not printing. That's the last image. The third one is printing. The other two are to provide a wider view of what the whole object looks like.

**Comment by nizarmah** [comment]
Sorry for the really late reply. And there's no error at all in the console? That's weird...

It might be related to the day being `07` and not just `7`. That's the only thing I have in mind. Because I bombarded this codepen example (https://codepen.io/nizarmah/pen/LkjjWV) with more than 1000 dummy data and I couldn't recreate the error.

So, it is most likely the `07`. It probably should be `7` instead. Please try it and let me know @sbennett08 .

**Comment by Bennett-Seth** [comment]
Eureka! That did it :) Thanks! Looks great now.

**Comment by nizarmah** [comment]
I'm glad :) Sorry again for the delayed response. If there's anything else, please let me know :+1:
