### ISSUE TITLE
The Calendar and Organizer do not show the data when pulled from Database

### ISSUE THREAD

**Issue by NightlandDriver** [nizarmah/calendar-javascript-lib#23]
**Describe the bug**
The Calendar and Organizer do not show the data.

**To Reproduce**
Sourcecode: https://pastebin.com/n2jDpg8t

**Expected behavior**
The Calendar and Organizer should show the data.

**Screenshots**
Site: https://ibb.co/Vmy09CM
Database: https://ibb.co/ccZ70Yw

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox, Edge(New)
 - Version 84.0, 87.0.664.60

**Additional context**
No Errors in the Console.

**Comment by nizarmah** [comment]
Hello @NightlandDriver, I noticed you closed the issue, I was wondering if the problem was resolved or not. Please let me know 😄

**Comment by NightlandDriver** [comment]
Yes, the problem has been solved
