### ISSUE TITLE
Google calendar Id

### ISSUE THREAD

**Issue by kuropanda24** [nizarmah/calendar-javascript-lib#5]
Is it possible to get the events from google calendar  and import it to this one?

**Comment by nizarmah** [comment]
Hello,

I absolutely adore the idea; I don't know why I didn't look into it before. It is currently very late. I'll look into it tomorrow and let you know. I might even set up a full documentation for it. Hopefully, it will be possible.

Have a wonderful day, and thanks for the suggestion.

**Comment by nizarmah** [comment]
Reviewing the Google Calendar API, one can change the JSON data format to one similar to my Calendar's format given in the README.md.
Therefore, I won't be giving any documentation to that; however, I'll keep the issue open until it works, in case you need to ask any questions.

**Comment by kuropanda24** [comment]
Sorry I tried doing that but it keeps giving me issues if you can give me example how to do it. Thanks

**Comment by kuropanda24** [comment]
data = {

                     2018: {
                         1: {
                             2: [
                                 {
                                     startTime: "2:00",
                                     endTime: "3:00",
                                     text: "xmas"
                                 }
                             ]
                         }
                     },
                     { 2018: {
                               3: {
                                    2: [
                                        {
                                            startTime: "2:00",
                                            endTime: "3:00",
                                            text: "xmas"
                                        }
                                    ]
                                }
                            }

}                   }


console.log(data);
                 				return data;

I tried manually putting information but only the last one shows up.

**Comment by nizarmah** [comment]
I'm sorry, this week I can't offer any help. I am too busy with college and work.
Your problem with the JSON could be easily solved by rereading the README carefully.

Good luck!
