### ISSUE TITLE
[question] License

### ISSUE THREAD

**Issue by ndossche** [nizarmah/calendar-javascript-lib#8]
Hi

I was wondering what the license of this project is.

Thanks in advance

**Comment by nizarmah** [comment]
Hello,

Thanks for pointing it out. I just added the GNU License. You're free to do with it whatever you want.
If you're gonna use it on some website or commercial product, kindly reopen this issue and send me a preview; I would love to see how I contributed. 

Have a wonderful day!

**Comment by enlivenapp** [comment]
You might consider the MIT license if you haven't already.

**Comment by nizarmah** [comment]
Hmm, I haven't no. But thanks for the suggestion, for after looking into it, this is the license I will use. Have a good day.
